name: angular_dart_demo
version: 0.0.1
dependencies:
  angular: '>=0.9.10'
  browser: any
  js: any
  shadow_dom: any
  google_kiwiflag_v1_api:
     path: ../dart_kiwiflag_v1_api_client


dev_dependencies:
  unittest: any
